name: publish

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Build with Gradle
      run: |
        echo -n "${{ secrets.GPG_KEY_ARMOR }}" | gpg --quiet --output secring.gpg --dearmor -
        ./gradlew publishMavenJavaPublicationToGitHubPackagesRepository publishToSonatype closeAndReleaseSonatypeStagingRepository \
          -PsonatypeUsername=${{ secrets.SONATYPE_USERNAME }} \
          -PsonatypePassword="${{ secrets.SONATYPE_PASSWORD }}" \
          -Psigning.keyId=${{ secrets.GPG_KEY_ID }} \
          -Psigning.password="${{ secrets.GPG_PASSWORD }}" \
          -Psigning.secretKeyRingFile=secring.gpg \
          -PgithubUsername=${{ secrets.RELEASE_USERNAME }} \
          -PgithubPassword="${{ secrets.RELEASE_TOKEN }}"
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
